### ISSUE TITLE
Font cut off

### ISSUE THREAD

**Issue by Scoutman01** [TF2HUDsArchive/Broesel-Hud#1]
When using the old surface font, the numbers 3 cut off on targetid and spec tournament

https://imgur.com/a/QxBjmU1

changing surface15 to surface16 fix the issue for both spectatorguihealth and spectatortournamentguihealth

**Comment by Scoutman01** [comment]
also for the chargeamount, SurfaceNumbers-Medium would be better or you can increase the wide value to 28 (for the old surface font)

**Comment by Hypnootize** [comment]
I ended up going for the hard way and rework how some of the fonts worked, the old surface font is now a proper verion of surface-medium and I also ended up changing some of the other font names since there were always conflicts with the m0rehud font names when installed on windows for example (both used surface-medium as name but they were different). Either way it should all be fixed now hopefully, I haven't seen any major font cut offs so far.

**Comment by Scoutman01** [comment]
CapNumPlayers isn't centered anymore

before:
![20200824185154_1](https://user-images.githubusercontent.com/50184129/91074191-7dba2980-e63c-11ea-8fb2-332bb45d1a67.jpg)
![20200824184918_1](https://user-images.githubusercontent.com/50184129/91074210-83b00a80-e63c-11ea-9534-0bbe77bf9112.jpg)
after:
![20200824185136_1](https://user-images.githubusercontent.com/50184129/91074255-8d397280-e63c-11ea-9d43-e1613bce3635.jpg)

here what it used to be:

"CapNumPlayers"
	{	
		"ControlName"			"Label"
		"fieldName"				"CapNumPlayers"
		"font"					"surface18"
		"xpos"					"5"
		"ypos"					"-5"
		"zpos"					"4"
		"wide"					"23"
		"tall"					"36"
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"labelText"				"%numcappers%"
		"textAlignment"			"center"
		"dulltext"				"0"
		"brighttext"			"0"
		"fgcolor_override"		"0 0 0 255"
	}

**Comment by Hypnootize** [comment]
Oh right I completely forgot that font was used there too, its fixed now ty

**Comment by Scoutman01** [comment]
just in huddemomanpipes, chargelabel change enabled to 0. Everything else seems good, thanks a lot !

**Comment by Hypnootize** [comment]
Thats also fixed now!
